---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: cicd-pipeline
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31988
  type: NodePort
  sessionAffinity: None
...
