---
- name: 'Copy over the manifest files'
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "./{{ item }}"
    owner: "{{ svc_acct_name}}"
    group: "{{ svc_acct_name}}"
    mode: '0640'
  loop:
    - 
    # - 'nginx-deployment.yaml'
    # - 'nginx-service.yaml'

- name: 'Apply the manifests'
  ansible.builtin.shell: "kubectl apply -f {{ item }}"
  changed_when: false
  loop:
    # - 'nginx-deployment.yaml'
    # - 'nginx-service.yaml'

- name: 'Pause 1 minute to allow pods to startup'
  ansible.builtin.pause:
    minutes: 1

- name: 'Get Pods'
  ansible.builtin.shell: "kubectl get pods -n cicd-pipeline"
  changed_when: false
  register: _shell_results

- name: 'Show output of Pods'
  ansible.builtin.debug:
    var: _shell_results.stdout

- name: 'Verify Pods are Ready'
  ansible.builtin.assert:
    that: "'Running' in _shell_results.stdout"
    fail_msg: "Pods are Showing Not Ready"
    success_msg: "Pods are running"

- name: 'Get the service IP address'
  ansible.builtin.shell: "kubectl get service nginx-service -n cicd-pipeline | grep nginx | awk '{ print $3 }'"
  register: _nginx_ip

- name: 'Display the nginx IP address'
  ansible.builtin.debug:
    var: _nginx_ip
...
