---
- block:
    - ansible.builtin.set_fact:
        _retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"

    - name: 'Kill Tunnel'
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          kill `ps -ef | grep 'ec2-instance-connect' | head -1 | awk '{ print $2 }'`
        executable: /bin/bash
      changed_when: false
      vars:
        ansible_become: false
      ignore_errors: true

    - name: 'Pause 5 seconds'
      ansible.builtin.pause:
        seconds: 5

    - name: 'Setup Tunnel'
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          aws ec2-instance-connect open-tunnel --instance-id {{ _instanceID }} --local-port "{{ '222' + _targetIP.split('.')[-1][:-1]  }}" &
        executable: /bin/bash
      changed_when: false
      register: _tunnel_output
      until: "'Listening for connections' in _tunnel_output.stdout"
      delay: 30
      retries: 2

    - name: 'Pause 10s'
      ansible.builtin.pause:
        seconds: 10
  rescue:
    - ansible.builtin.fail:
        msg: 'Maximum retries reached.'
      when: _retry_count | int == 5

    - ansible.builtin.include_tasks: 'include_tasks/configure_tunnel_aws.yml'
...
