---
- name: 'Get info for test-c1-cp1-nic1'
  azure.azcollection.azure_rm_resource_info:
    api_version: '2024-03-01'
    resource_group: "{{ resource_group }}"
    provider: 'network'
    resource_type: 'networkInterfaces'
    resource_name: 'test-c1-cp1-nic1'
  register: _netint_c1_cp1_nic1

- debug:
    var: _netint_c1_cp1_nic1

- name: 'Get IP address for test-c1-cp1'
  ansible.builtin.set_fact:
    _test_c1_cp1_nic1_ip: "{{ _netint_c1_cp1_nic1 | json_query(_query) }}"
  vars:
    _query: "response[].properties.ipConfigurations[].properties.privateIPAddress | [0]"

- debug:
    var: _test_c1_cp1_nic1_ip

- name: 'Get info for test-c1-node1-nic1'
  azure.azcollection.azure_rm_resource_info:
    api_version: '2024-03-01'
    resource_group: "{{ resource_group }}"
    provider: 'network'
    resource_type: 'networkInterfaces'
    resource_name: 'test-c1-node1-nic1'
  register: _netint_c1_node1_nic1

- name: 'Get IP address for test-c1-node1-nic1'
  ansible.builtin.set_fact:
    _test_c1_node1_nic1_ip: "{{ _netint_c1_node1_nic1 | json_query(_query) }}"
  vars:
    _query: "response[].properties.ipConfigurations[].properties.privateIPAddress | [0]"

- debug:
    var: _test_c1_node1_nic1_ip

- name: 'Get info for test-c1-node2-nic1'
  azure.azcollection.azure_rm_resource_info:
    api_version: '2024-03-01'
    resource_group: "{{ resource_group }}"
    provider: 'network'
    resource_type: 'networkInterfaces'
    resource_name: 'test-c1-node2-nic1'
  register: _netint_c1_node2_nic1

- name: 'Get IP address for test-c1-node2-nic1'
  ansible.builtin.set_fact:
    _test_c1_node2_nic1_ip: "{{ _netint_c1_node2_nic1 | json_query(_query) }}"
  vars:
    _query: "response[].properties.ipConfigurations[].properties.privateIPAddress | [0]"

- debug:
    var: _test_c1_node2_nic1_ip

- name: 'Get info for test-c1-node3-nic1'
  azure.azcollection.azure_rm_resource_info:
    api_version: '2024-03-01'
    resource_group: "{{ resource_group }}"
    provider: 'network'
    resource_type: 'networkInterfaces'
    resource_name: 'test-c1-node3-nic1'
  register: _netint_c1_node3_nic1

- name: 'Get IP address for test-c1-node3-nic1'
  ansible.builtin.set_fact:
    _test_c1_node3_nic1_ip: "{{ _netint_c1_node3_nic1 | json_query(_query) }}"
  vars:
    _query: "response[].properties.ipConfigurations[].properties.privateIPAddress | [0]"

- debug:
    var: _test_c1_node3_nic1_ip
...
