---
- name: 'Get info for test-c1-cp1-nic1'
  amazon.aws.ec2_instance_info:
    filters:
      "tag:Name": test-c1-cp1
  register: _test_c1_cp1

- debug:
    var: _test_c1_cp1

- name: 'Get IP address for test-c1-cp1'
  ansible.builtin.set_fact:
    _test_c1_cp1_nic1_ip: "{{ _test_c1_cp1 | json_query(_query) }}"
  vars:
    _query: "instances[].network_interfaces[].private_ip_address | [0]"

- name: 'Get instance ID for test-c1-cp1'
  ansible.builtin.set_fact:
    _test_c1_cp1_instance_id: "{{ _test_c1_cp1 | json_query(_query) }}"
  vars:
    _query: "instances[].instance_id | [0]"

- debug:
    var: _test_c1_cp1_nic1_ip

- debug:
    var: _test_c1_cp1_instance_id
...
