---
- name: 'Create the cattle-system namespace'
  ansible.builtin.shell: "kubectl create namespace cattle-system"
  changed_when: false

- name: 'Install Rancher'
  ansible.builtin.shell: "helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=rancher"
  changed_when: false

- name: 'Pause 1 minute'
  ansible.builtin.pause:
    minutes: 1

- name: 'Verify installation was successful'
  ansible.builtin.shell: "kubectl -n cattle-system rollout status deploy/rancher"
  register: _rancher_results
  until: "'successfully rolled out' in _rancher_results.stdout"
  retries: 25
  delay: 15
...